### PR TITLE
changes on footer

### PR DESCRIPTION
**Pull request by ahamed001**

### CODE REVIEW

**Comment by moFazil** [comment]
thank u

**Review by moFazil — APPROVED** [review]
thanks dolare

**Review by moFazil — APPROVED** [review]

**Review by moFazil — CHANGES_REQUESTED** [review]
dank

**Review by ahamed001 — COMMENTED** [review]
danq2

**Review by moFazil — APPROVED** [review]

**Review by moFazil — APPROVED** [review]

**Review by moFazil — APPROVED** [review]

**Review by moFazil — APPROVED** [review]

**Review by moFazil — APPROVED** [review]

**Pull request merged**
